//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 12-Apr-16 12:36:09 PM
namespace HarryPotter
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Assets
        {
            
            /// <summary> Path to Content/Assets/Font.TTF </summary>
            public const string Font_TTF = "Content/Assets/Font.TTF";
            
            /// <summary> Path to Content/Assets/Obstacles.xml </summary>
            public const string Obstacles_xml = "Content/Assets/Obstacles.xml";
            
            public sealed class Music
            {
                
                /// <summary> Path to Content/Assets/Music/music.mp3 </summary>
                public const string music_mp3 = "Content/Assets/Music/music.mp3";
            }
            
            public sealed class Sprites
            {
                
                /// <summary> Path to Content/Assets/Sprites/BackgroundBoard.png </summary>
                public const string BackgroundBoard_png = "Content/Assets/Sprites/BackgroundBoard.png";
                
                /// <summary> Path to Content/Assets/Sprites/Button.png </summary>
                public const string Button_png = "Content/Assets/Sprites/Button.png";
                
                /// <summary> Path to Content/Assets/Sprites/ButtonOver.png </summary>
                public const string ButtonOver_png = "Content/Assets/Sprites/ButtonOver.png";
                
                /// <summary> Path to Content/Assets/Sprites/CastleBoard.png </summary>
                public const string CastleBoard_png = "Content/Assets/Sprites/CastleBoard.png";
                
                /// <summary> Path to Content/Assets/Sprites/Explosion.spritesheet </summary>
                public const string Explosion_spritesheet = "Content/Assets/Sprites/Explosion.spritesheet";
                
                /// <summary> Path to Content/Assets/Sprites/GroundUnitBoard.spritesheet </summary>
                public const string GroundUnitBoard_spritesheet = "Content/Assets/Sprites/GroundUnitBoard.spritesheet";
                
                /// <summary> Path to Content/Assets/Sprites/Harry.spritesheet </summary>
                public const string Harry_spritesheet = "Content/Assets/Sprites/Harry.spritesheet";
                
                /// <summary> Path to Content/Assets/Sprites/Magic.spritesheet </summary>
                public const string Magic_spritesheet = "Content/Assets/Sprites/Magic.spritesheet";
                
                /// <summary> Path to Content/Assets/Sprites/MagicBoard.png </summary>
                public const string MagicBoard_png = "Content/Assets/Sprites/MagicBoard.png";
                
                /// <summary> Path to Content/Assets/Sprites/MenuOver.png </summary>
                public const string MenuOver_png = "Content/Assets/Sprites/MenuOver.png";
                
                /// <summary> Path to Content/Assets/Sprites/particle.png </summary>
                public const string particle_png = "Content/Assets/Sprites/particle.png";
                
                /// <summary> Path to Content/Assets/Sprites/SkyBoard.png </summary>
                public const string SkyBoard_png = "Content/Assets/Sprites/SkyBoard.png";
                
                /// <summary> Path to Content/Assets/Sprites/StartMenuBackground.jpg </summary>
                public const string StartMenuBackground_jpg = "Content/Assets/Sprites/StartMenuBackground.jpg";
                
                /// <summary> Path to Content/Assets/Sprites/WaveLogo.png </summary>
                public const string WaveLogo_png = "Content/Assets/Sprites/WaveLogo.png";
                
                /// <summary> Texture names from spritesheet Content/Assets/Sprites/Explosion.spritesheet </summary>
                public struct Explosion_spritesheet_TextureName
                {
                    
                    public const string explosion_0 = "explosion_0";
                    
                    public const string explosion_1 = "explosion_1";
                    
                    public const string explosion_10 = "explosion_10";
                    
                    public const string explosion_2 = "explosion_2";
                    
                    public const string explosion_3 = "explosion_3";
                    
                    public const string explosion_4 = "explosion_4";
                    
                    public const string explosion_5 = "explosion_5";
                    
                    public const string explosion_6 = "explosion_6";
                    
                    public const string explosion_7 = "explosion_7";
                    
                    public const string explosion_9 = "explosion_9";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Sprites/GroundUnitBoard.spritesheet </summary>
                public struct GroundUnitBoard_spritesheet_TextureName
                {
                    
                    public const string _0 = "0";
                    
                    public const string _1 = "1";
                    
                    public const string _10 = "10";
                    
                    public const string _2 = "2";
                    
                    public const string _3 = "3";
                    
                    public const string _4 = "4";
                    
                    public const string _5 = "5";
                    
                    public const string _6 = "6";
                    
                    public const string _7 = "7";
                    
                    public const string _8 = "8";
                    
                    public const string _9 = "9";
                    
                    public const string _11 = "11";
                    
                    public const string _12 = "12";
                    
                    public const string _13 = "13";
                    
                    public const string _14 = "14";
                    
                    public const string _15 = "15";
                    
                    public const string _16 = "16";
                    
                    public const string _17 = "17";
                    
                    public const string _18 = "18";
                    
                    public const string _19 = "19";
                    
                    public const string _20 = "20";
                    
                    public const string _21 = "21";
                    
                    public const string _22 = "22";
                    
                    public const string _23 = "23";
                    
                    public const string _24 = "24";
                    
                    public const string _25 = "25";
                    
                    public const string _26 = "26";
                    
                    public const string _27 = "27";
                    
                    public const string _28 = "28";
                    
                    public const string _29 = "29";
                    
                    public const string _30 = "30";
                    
                    public const string _31 = "31";
                    
                    public const string _32 = "32";
                    
                    public const string _33 = "33";
                    
                    public const string _34 = "34";
                    
                    public const string _35 = "35";
                    
                    public const string _36 = "36";
                    
                    public const string _37 = "37";
                    
                    public const string _38 = "38";
                    
                    public const string _39 = "39";
                    
                    public const string _40 = "40";
                    
                    public const string _41 = "41";
                    
                    public const string _42 = "42";
                    
                    public const string _43 = "43";
                    
                    public const string _44 = "44";
                    
                    public const string _45 = "45";
                    
                    public const string _46 = "46";
                    
                    public const string _47 = "47";
                    
                    public const string _48 = "48";
                    
                    public const string _49 = "49";
                    
                    public const string _50 = "50";
                    
                    public const string _51 = "51";
                    
                    public const string _52 = "52";
                    
                    public const string _53 = "53";
                    
                    public const string _54 = "54";
                    
                    public const string _55 = "55";
                    
                    public const string _56 = "56";
                    
                    public const string _57 = "57";
                    
                    public const string _58 = "58";
                    
                    public const string _59 = "59";
                    
                    public const string _60 = "60";
                    
                    public const string _100 = "100";
                    
                    public const string _101 = "101";
                    
                    public const string _102 = "102";
                    
                    public const string _103 = "103";
                    
                    public const string _104 = "104";
                    
                    public const string _105 = "105";
                    
                    public const string _106 = "106";
                    
                    public const string _107 = "107";
                    
                    public const string _108 = "108";
                    
                    public const string _109 = "109";
                    
                    public const string _110 = "110";
                    
                    public const string _111 = "111";
                    
                    public const string _112 = "112";
                    
                    public const string _113 = "113";
                    
                    public const string _61 = "61";
                    
                    public const string _62 = "62";
                    
                    public const string _63 = "63";
                    
                    public const string _64 = "64";
                    
                    public const string _65 = "65";
                    
                    public const string _66 = "66";
                    
                    public const string _67 = "67";
                    
                    public const string _68 = "68";
                    
                    public const string _69 = "69";
                    
                    public const string _70 = "70";
                    
                    public const string _71 = "71";
                    
                    public const string _72 = "72";
                    
                    public const string _73 = "73";
                    
                    public const string _74 = "74";
                    
                    public const string _75 = "75";
                    
                    public const string _76 = "76";
                    
                    public const string _77 = "77";
                    
                    public const string _78 = "78";
                    
                    public const string _79 = "79";
                    
                    public const string _80 = "80";
                    
                    public const string _81 = "81";
                    
                    public const string _82 = "82";
                    
                    public const string _83 = "83";
                    
                    public const string _84 = "84";
                    
                    public const string _85 = "85";
                    
                    public const string _86 = "86";
                    
                    public const string _87 = "87";
                    
                    public const string _88 = "88";
                    
                    public const string _89 = "89";
                    
                    public const string _90 = "90";
                    
                    public const string _91 = "91";
                    
                    public const string _92 = "92";
                    
                    public const string _93 = "93";
                    
                    public const string _94 = "94";
                    
                    public const string _95 = "95";
                    
                    public const string _96 = "96";
                    
                    public const string _97 = "97";
                    
                    public const string _98 = "98";
                    
                    public const string _99 = "99";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Sprites/Harry.spritesheet </summary>
                public struct Harry_spritesheet_TextureName
                {
                    
                    public const string harry_down0 = "harry_down0";
                    
                    public const string harry_down1 = "harry_down1";
                    
                    public const string harry_down2 = "harry_down2";
                    
                    public const string harry_down3 = "harry_down3";
                    
                    public const string harry_down4 = "harry_down4";
                    
                    public const string harry_down5 = "harry_down5";
                    
                    public const string harry_up0 = "harry_up0";
                    
                    public const string harry_up1 = "harry_up1";
                    
                    public const string harry_up2 = "harry_up2";
                    
                    public const string harry_up3 = "harry_up3";
                    
                    public const string harry_up4 = "harry_up4";
                    
                    public const string harry_up5 = "harry_up5";
                }
                
                /// <summary> Texture names from spritesheet Content/Assets/Sprites/Magic.spritesheet </summary>
                public struct Magic_spritesheet_TextureName
                {
                    
                    public const string magic_0 = "magic_0";
                    
                    public const string magic_1 = "magic_1";
                }
                
                public sealed class Obstacles
                {
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle1.png </summary>
                    public const string obstacle1_png = "Content/Assets/Sprites/Obstacles/obstacle1.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle10.png </summary>
                    public const string obstacle10_png = "Content/Assets/Sprites/Obstacles/obstacle10.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle11.png </summary>
                    public const string obstacle11_png = "Content/Assets/Sprites/Obstacles/obstacle11.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle12.png </summary>
                    public const string obstacle12_png = "Content/Assets/Sprites/Obstacles/obstacle12.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle13.png </summary>
                    public const string obstacle13_png = "Content/Assets/Sprites/Obstacles/obstacle13.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle14.png </summary>
                    public const string obstacle14_png = "Content/Assets/Sprites/Obstacles/obstacle14.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle15.png </summary>
                    public const string obstacle15_png = "Content/Assets/Sprites/Obstacles/obstacle15.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle2.png </summary>
                    public const string obstacle2_png = "Content/Assets/Sprites/Obstacles/obstacle2.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle3.png </summary>
                    public const string obstacle3_png = "Content/Assets/Sprites/Obstacles/obstacle3.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle4.png </summary>
                    public const string obstacle4_png = "Content/Assets/Sprites/Obstacles/obstacle4.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle5.png </summary>
                    public const string obstacle5_png = "Content/Assets/Sprites/Obstacles/obstacle5.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle6.png </summary>
                    public const string obstacle6_png = "Content/Assets/Sprites/Obstacles/obstacle6.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle7.png </summary>
                    public const string obstacle7_png = "Content/Assets/Sprites/Obstacles/obstacle7.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle8.png </summary>
                    public const string obstacle8_png = "Content/Assets/Sprites/Obstacles/obstacle8.png";
                    
                    /// <summary> Path to Content/Assets/Sprites/Obstacles/obstacle9.png </summary>
                    public const string obstacle9_png = "Content/Assets/Sprites/Obstacles/obstacle9.png";
                }
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Path to Content/Scenes/MyScene.wscene </summary>
            public const string MyScene = "Content/Scenes/MyScene.wscene";
        }
    }
}
